### ISSUE TITLE
ユーザー認証を作る

### ISSUE THREAD

**Issue by zeronosu77108** [jphacks/ON_1906#2]

**Comment by e165725** [comment]
https://qiita.com/bino98/items/596b5cffeca7c104bd90

**Comment by e165725** [comment]
細かいのが変わってるみたいなのでほかも見ながらやってます
http://oweleo.hatenablog.com/entry/2017/07/31/200236

**Comment by zeronosu77108** [comment]
https://qiita.com/hidepino/items/a1eb9d2f32ce33389f20

**Comment by e165725** [comment]
https://qiita.com/daichirata/items/da40e205d273ae69fcfc

**Comment by e165725** [comment]
https://qiita.com/NaokiIshimura/items/2a179f2ab910992c4d39

**Comment by e165725** [comment]
大まかな流れはここと一緒です.
bashでなく,credentials.yml.encに書いてます
https://qiita.com/hidepino/items/a1eb9d2f32ce33389f20
